# 机器学习实战
- Ch01 NumPy函数库

## 4x4随机数组

In [1]:
from numpy import *
random.rand(4, 4)

array([[0.93456641, 0.59304903, 0.13058081, 0.0242313 ],
       [0.72811921, 0.72148127, 0.06984023, 0.8866982 ],
       [0.92478083, 0.9948156 , 0.99089152, 0.50626664],
       [0.8639752 , 0.86496534, 0.14566022, 0.998176  ]])

## 4x4矩阵
## 矩阵求逆

In [2]:
randMat = mat(random.rand(4, 4))
randMat.I

matrix([[-1.25896811, -1.73299276,  1.80747763,  1.37449468],
        [-3.3946277 ,  0.0346969 ,  1.22608113,  1.97019716],
        [ 1.12641397,  1.24343968, -1.68296433,  0.51230729],
        [ 3.39080542,  1.08189665, -0.36719337, -4.04910462]])

## 矩阵*矩阵的逆

In [3]:
invRandMat = randMat.I
randMat*invRandMat

matrix([[ 1.00000000e+00, -2.77091641e-16,  2.04774525e-16,
         -2.26471845e-17],
        [ 3.96329997e-16,  1.00000000e+00, -1.94585591e-18,
          5.95307055e-17],
        [ 4.01246030e-16, -6.67674268e-18,  1.00000000e+00,
         -2.12149768e-16],
        [-7.08008666e-17, -2.51372273e-17,  3.61497537e-16,
          1.00000000e+00]])

## 矩阵简单运算

In [4]:
myEye = randMat*invRandMat
# eye为单位矩阵
myEye - eye(4)

matrix([[-1.11022302e-16, -2.77091641e-16,  2.04774525e-16,
         -2.26471845e-17],
        [ 3.96329997e-16,  0.00000000e+00, -1.94585591e-18,
          5.95307055e-17],
        [ 4.01246030e-16, -6.67674268e-18,  2.22044605e-16,
         -2.12149768e-16],
        [-7.08008666e-17, -2.51372273e-17,  3.61497537e-16,
          2.22044605e-16]])